on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Build

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build binary
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        goosarch:
          - 'darwin/amd64'
          - 'darwin/arm64'
          - 'freebsd/amd64'
          - 'freebsd/arm64'
          - 'linux/amd64'
          - 'linux/arm'
          - 'linux/arm64'
          - 'linux/mips'
          - 'linux/mips64'
          - 'linux/mips64le'
          - 'linux/mipsle'
          - 'linux/ppc64'
          - 'linux/ppc64le'
          - 'linux/riscv64'          
          - 'windows/amd64'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'
      - name: Get OS and arch info
        run: |
          GOOSARCH=${{matrix.goosarch}}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          BINARY_NAME=${{github.repository}}-$GOOS-$GOARCH
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV
      - name: Build
        run: |
          go build -o "$BINARY_NAME" -v
      - name: Release
        uses: softprops/action-gh-release@v1
        with:          
          draft: true          
          files: |
            ${{env.BINARY_NAME}}
            README.md
            .env.default
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
